### ISSUE TITLE
/fov

### ISSUE THREAD

**Issue by chopraaa** [Asunaya/RefinedGunz#15]
Does /fov change the field for everyone in the game?

If not, isn't this game breaking?

**Comment by Asunaya** [comment]
> Does /fov change the field for everyone in the game?

No.

> If not, isn't this game breaking?

You mean, like, that it gives you a competitive advantage because you can see more of the screen, or something? I guess that hasn't really occurred to me. Many multiplayer games let you change your FOV, AFAIK.

We could add a Config.h option to disable it if you want, I guess? o:

**Comment by chopraaa** [comment]
Yes, that's exactly what I mean. Unless fov is room-wide, I don't see any positive points to it. 

> We could add a Config.h option to disable it if you want, I guess? o:

Yes, that'd do.
