### ISSUE TITLE
Concerning your help with a certain project..

### ISSUE THREAD

**Issue by phugen** [Asunaya/RefinedGunz#22]
Hi,

because of the lack of a better contact option, I'm linking you the video you helped create by developing RGunz here because it enabled me to do various 3D animations. I owe you a huge thanks, and of course I mentioned you in the credits. Keep up the good work, and watch the outtake / behind-the-scenes video as well if you want to! 

https://www.youtube.com/watch?v=9r2pWYhy0p8

(I'll edit this issue later because obviously Github issues should rather be used for discussion relevant to the project.)

**Comment by Asunaya** [comment]
Those are both really cool videos. Thanks for sharing them with me! ^__^ I think that has to be the highest production value Gunz video ever.

I've added an email to my Github profile so that people can contact me more reasonably in the future. Sorry about that. :/
