### ISSUE TITLE
Issue with switching weapons

### ISSUE THREAD

**Issue by Cmdxz** [Asunaya/RefinedGunz#26]
I set next weapon to E and scroll down, and previous to Q and scroll up.

I notice it will glitch and if I have a sword out, I cannot use scroll or E/Q to change weapons..
But if I have my ranged weapons out, I can use it. but the moment it switched to sword, I can only use 1-2-3 to switch weapons.

Any ideas?

**Comment by Cmdxz** [comment]
edit : "Previous weapon" works any time, its just "next weapon" that does not.

**Comment by Asunaya** [comment]
Fixed in e4c85f9.
