### ISSUE TITLE
Only mansion quest map

### ISSUE THREAD

**Issue by Alemarfar** [Asunaya/RefinedGunz#28]
You can not select prison or dungeon.

**Comment by Jetman82** [comment]
I don't really program much anymore, and I don't have git on my pc atm, but from what I remember maiet hardcoded mansion in zstageinterface.cpp, it's a pointer that hardsets the mapname to mansion. remove the if/else, and just leave pointer->setmapname(szMapName). If you have any other issues with it let me know.

**Comment by dansheen21** [comment]
Hey @Jetman82 - I did this, and checked my other source to make sure it is correct, which it is. But I still can only choose Mansion - is there something else I need to do in the files?

**Comment by Jetman82** [comment]
Are you sure the xml files actually contain prison/dungeon mapsets? If they do, maybe check the parser cpp for quest and make sure it's grabbing those and not just doing some kind of hardcoded mansion grab.

**Comment by Asunaya** [comment]
Fixed in 4a6da73. I don't think the v0.6.0 release files has all of the scenarios and stuff, but you should be able to get them from 1.5 files (or wait until next release, when I'll add them). Thanks!
