### ISSUE TITLE
Effect not working?

### ISSUE THREAD

**Issue by dansheen21** [Asunaya/RefinedGunz#33]
Hey there @Asunaya 

I have noticed that on your source the effect doesn't work. I've tried putting effect.mrs in Sound/Effect while also having all the effect files in Sound.mrs/effect - The BGM doesn't have that issue but in the source they are all linking to the same location.

Also, every time I launch the game the checkbox for "narration voice play" isn't checked.

Any ideas?
Thanks.

**Comment by Asunaya** [comment]
Should be fixed with 41abb65 and df15911. Thanks!
