### ISSUE TITLE
Feature Request: AI?

### ISSUE THREAD

**Issue by CanadianJeff** [Asunaya/RefinedGunz#38]
anyone thinking about creating AI/BOTS to fight against

**Comment by TriForceX** [comment]
I definietly agree! 
i already did something for another game, so is really useful and fun, specially to practice or learn.
We should consider the most of combos and tricks to apply on BOTS (bf, dbf, ss, etc...)

**Comment by CanadianJeff** [comment]
closing because this is old and abandon feel free to reopen
