### ISSUE TITLE
Font texture corruption/artifacts

### ISSUE THREAD

**Issue by dotdeath** [Asunaya/RefinedGunz#39]
I've just stumbled upon this repository and I am really impressed by the work done here, thank you for posting this as an open-source project.

I would like to report an issue I faced.

**Brief information:**
Texture corruption when switching menus. Most prominent when in-game.

**When does it happen?**
After typing some messages in-game, all the font textures start producing artifacts. It happens very quickly only when in-game. It can be triggered by opening and closing the settings menu, or even turning on the hitbox debugging info. Eventually it starts being more prominent.

**Screenshots:**
![image](https://user-images.githubusercontent.com/8302065/69477330-ec552700-0e1f-11ea-9ac3-cbe39212dabf.png)
Artifacts appearing next to fonts.

![image](https://user-images.githubusercontent.com/8302065/69477343-0ee74000-0e20-11ea-982e-a4e5d3e4e483.png)
Artifacts appearing heavily here.

**Comment by TriForceX** [comment]
Have you tried in a standard 4:3 resolution?

**Comment by dotdeath** [comment]
Yes, it gives the same result.

**Comment by dotdeath** [comment]
Fixed - driver issue. Changed driver settings to use application's settings for Antialiasing and Anisotropic filtering.
